name: Publish Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
      - run: npm i -g npm@latest
      - run: npm -v
      - run: npm install
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          cache: "npm"
      - run: npm i -g npm@latest
      - run: npm -v
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
# Use to publish to npm
# publish-2:
#   needs: build
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v2
#       with:
#         node-version: 12
#         registry-url: https://registry.npmjs.org/
#     - run: npm ci
#     - run: npm publish --access public
#       env:
#         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
